version: '3.3'

services:
  web:
    image: bix
    container_name: bix_web
    build: .
    command: sh -c "sleep 5 && python manage.py migrate && 
                    python manage.py runserver 0.0.0.0:8000"
    expose:
      - 80
    depends_on:
      - postgres
      - redis
    links:
      - postgres:postgres
      - redis:redis
    env_file:
      - .env
  redis:
    container_name: redis
    restart: on-failure
    image: redis:alpine
    depends_on:
      - postgres
    volumes:
      - redisdata:/data
  celery-worker:
    container_name: celery-worker
    build: .
    command: celery -A bix worker -l INFO
    depends_on:
      - web
  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A bix beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres:12.4-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bd_bix
  nginx:
    container_name: nginx
    restart: on-failure
    build: ./nginx/
    ports:
      - "8000:8000"
    depends_on:
      - web
    links:
      - web:web

volumes:
  pgdata:
  redisdata:
